name: Setup Ci

inputs:
  node-version:
    required: false
    default: 18

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Cache node_modules
      id: cache-node_modules
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: node_modules-${{ runner.os }}-node-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
    - if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
      run: npm ci
      shell: bash
