name: Automated Fixes
on:
  workflow_call:
    secrets:
      BOT_REPO_SCOPED_TOKEN:
        required: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - uses: ./.github/setup-ci
      - run: npx pages generate features
        working-directory: apps/test-site
      - run: npx pages generate features
        working-directory: e2e-tests
      - run: npm run autofix
      - name: Automated Linting
        id: automated-linting
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated linting update and features.json sync"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions
      - name: Fail on linting push
        run: |
          if [[ ${{ steps.automated-linting.outputs.pushed }} == true ]]; then exit 1; else exit 0; fi

  license-check:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g json@v11
      - run: npm install -g generate-license-file@2
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - name: Generate third party notices
        run: ./generate-third-party-notices.sh
      - name: Update THIRD-PARTY-NOTICES
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update to THIRD-PARTY-NOTICES from github action's 3rd party notices check"
          add: '["packages/studio/THIRD-PARTY-NOTICES", "packages/studio-plugin/THIRD-PARTY-NOTICES"]'
          push: true
          default_author: github_actions
