name: Playwright Tests

on: push

jobs:
  test:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm run build -w=packages/studio
      - uses: actions/cache@v3
        with:
          path: ~/Library/Caches/ms-playwright
          key: playwright-browsers-${{ hashFiles('node_modules/@playwright/test/package.json') }}
      - run: npx playwright install
      - run: npm i
      - name: Run Playwright
        run: npm run playwright
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: playwright-report
          path: ./e2e-tests/playwright-report/
          retention-days: 30
