name: Playwright Tests

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: false
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm run build -w=packages/studio
      - run: npx playwright install
      - run: npm i
      - run: git config --global user.email "slapshot-github-actions@yext.com"
      - run: git config --global user.name "Slap"
      - run: npm run playwright

      # This step will commit any new snapshots that weren't taken locally.
      # i.e. snapshots for Windows
      - name: Commit New Snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ failure() && github.ref_name != 'main' }}
        with:
          message: Commit new snapshots for ${{ matrix.os }}
          add: ./e2e_tests/__screenshots__/*
          push: true
          pull: --rebase --autostash
          default_author: github_actions 

      - name: Upload Playwright Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-reports-${{ matrix.os }}
          path: ./e2e-tests/playwright-report/
          retention-days: 30
