name: Playwright Tests

on:
  push:
    branches: main
  pull_request:


jobs:
  acceptance:
    name: (${{ matrix.shard }}/3)
    timeout-minutes: 30
    strategy:
      matrix:
        shard: [1, 2, 3]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm run build -w=packages/studio
      - uses: actions/cache@v3
        with:
          path: ~/Library/Caches/ms-playwright
          key: playwright-browsers-${{ hashFiles('node_modules/@playwright/test/package.json') }}
      - run: npx playwright install
      - run: npm i

      - run: npm run playwright -- --shard=${{ matrix.shard }}/3
        working-directory: e2e-tests
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: playwright-report-shard-${{matrix.shard}}
          path: ./e2e-tests/playwright-report/
          retention-days: 30
