name: Playwright Tests

on:
  push:
    branches: main
  pull_request:

jobs:
  acceptance:
    name: ${{ matrix.os }} (${{ matrix.shard }}/3)
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm run build -w=packages/studio
      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/ms-playwright
            %USERPROFILE%\AppData\Local\ms-playwright
          key: playwright-browsers_${{ runner.os }}-${{ hashFiles('node_modules/@playwright/test/package.json') }}
      - run: npx playwright install
      - run: npm i
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm run playwright -- --shard=${{ matrix.shard }}/3
        working-directory: e2e-tests
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: playwright-report--${{ matrix.os }}-${{matrix.shard}}
          path: ./e2e-tests/playwright-report/
          retention-days: 30

      # This step will commit any new snapshots that weren't taken locally.
      - name: Commit New Snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          message: New snapshots for ${{ matrix.os }} ${{ matrix.shard }} of 3
          add: e2e-tests/__screenshots__/*.png
          push: true
          pull: --rebase --autostash
          default_author: github_actions
