name: Root Workflow

on: pull_request

jobs:
  automated-fixes: 
    uses: ./.github/workflows/autofixes.yml
    secrets: inherit

  run-tests:
    needs: automated-fixes
    uses: ./.github/workflows/run-tests.yml
