name: Root Workflow

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  automated-fixes: 
    uses: ./.github/workflows/autofixes.yml
    secrets: inherit

  run-tests:
    needs: automated-fixes
    uses: ./.github/workflows/run-tests.yml

  playwright:
    needs: automated-fixes
    uses: ./.github/workflows/playwright.yml
