name: Run Tests

on:
  push:
    branches: main
  pull_request:


jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [16.x, 18.x, 19.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm test -w=packages/studio-plugin
      - run: npm test -w=packages/studio
        if: success() || failure()

  test_build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run typecheck-jest
