name: Run Tests

on: [push, pull_request]

jobs:
  unit_tests:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run_tests.yml@v1
    with:
      node_matrix: '["16.x", "18.x", "19.x"]'
      build_script: ''
  build:
    steps:
      - run: npm i
      - run: npm run build
