name: Run Tests

on: [push, pull_request]

jobs:
  unit_tests:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run_tests.yml@v1
    with:
      node_matrix: '["16.x", "18.x", "19.x"]'
      build_script: "npm run build -w=packages/studio-plugin"

  test_build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --ignore-scripts
      - run: npm rebuild
      - run: npm run build
      - run: npm run typecheck-jest
