name: Run Tests
on: workflow_call

jobs:
  studio-ui:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm run build -w=packages/studio-plugin
      - run: npm test -w=packages/studio-ui -- --coverage=false

  studio_plugin:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm test -w=packages/studio-plugin -- --coverage=false

  test_build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-ci
      - run: npm run build
      - run: npm run build-test-site -w=apps/test-site
      - run: npm run typecheck-jest
