name: Run Tests

on: [push, pull_request]

jobs:
  tests:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run_tests.yml@v1
    with:
      build_script: |
        npm i -D react@16.14 react-dom@16.14
        npm run build
      node_matrix: '["16.x", "18.x", "19.x"]'