name: Run Tests

on: pull_request

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      - run: cd studio && npm ci
      - run: cd studio && npm run test

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
      # build studio
      - run: cd studio && npm ci && npx tsc
      # build plugin
      - run: cd search-ui-react-plugin && npm ci && npm run build

