name: Check and Update Third Party Notices
on: workflow_call

jobs:
  license-check:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g generate-license-file@1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      - run: npm install
      - run: cd packages/studio; ../../generate-third-party-notices.sh
      - run: cd packages/studio/plugin; ../../generate-third-party-notices.sh
      - name: Update THIRD-PARTY-NOTICES
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update to THIRD-PARTY-NOTICES from github action's 3rd party notices check"
          add: '["packages/studio/THIRD-PARTY-NOTICES", "packages/studio-plugin/THIRD-PARTY-NOTICES"]'
          push: true
          default_author: github_actions
