name: Check and Update Third Party Notices
on: workflow_call

jobs:
  license-check:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g generate-license-file@1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.BOT_REPO_SCOPED_TOKEN }}
      # Skip post-install scripts here, as a malicious
      # script could steal the NPM_TOKEN.
      - run: cd packages/studio; npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild
      - run: generate-license-file --input package.json --output THIRD-PARTY-NOTICES --overwrite
      
      - run: cd ../studio-plugin; npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm rebuild
      - run: generate-license-file --input package.json --output THIRD-PARTY-NOTICES --overwrite

      - name: Update THIRD-PARTY-NOTICES
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update to THIRD-PARTY-NOTICES from github action's 3rd party notices check"
          add: 'THIRD-PARTY-NOTICES'
          push: true
          default_author: github_actions